# This is a basic workflow to help you get started with Actions



# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches:  
       - main 
    paths:
       - 'templates/aws_template.json' 
 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run packer container - Build & deploy

      # Initialize Packer templates
      - name: Initialize Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: init 

      # Runs a set of commands using the runners shell
      - uses: hashicorp/packer-github-actions@master
        env: 
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY}}
          AWS_SECRET_KEY: ${{ secret.AWS_SECRET_KEY }}
        with:
          args: "build /github/workspace/templates/aws_template.json"

      